### ISSUE TITLE
Unit testing?

### ISSUE THREAD

**Issue by mhf-ir** [igniphp/framework#7]
Any documentation for test unit ?

**Comment by dkraczkowski** [comment]
@mhf-ir What do you mean?

**Comment by mhf-ir** [comment]
if loop run forever how write a sample test unit to create request and mock server dispatch the request and server shutdown after test.

**Comment by dkraczkowski** [comment]
@mhf-ir Testing server shutdown should be as simple as testing your shutdown event class (the one that extends `\Igni\Http\Server\OnShutdown`)-  you can mockup the `\Igni\Http\Server` class in your code in order to achieve this.

Testing your controllers should be similar, you simply declare your test class instantiate your controller (which extends HttpController) and mockup Request class.  

Entire application layer with the server flow is already tested in the framework so you don't have to worry about that part.

**Comment by dkraczkowski** [comment]
I can provide example code to help you out.

**Comment by mhf-ir** [comment]
That's will be awesome, try to using non-block swoole base is new and many developers using Chinease platfroms but it's not documentations well like https://github.com/swoft-cloud/swoft.
Documentation and support will be the point.

Thank you for support

**Comment by dkraczkowski** [comment]
@mhf-ir https://github.com/igniphp/framework/tree/master/docs#testing
